# Setup
title:            Liquid Rocket Motor Development
tagline:          'version 1'
description:      'Richard Helper'
url:              https://richardhelpermotor.github.io
baseurl:          ""
paginate:         5

# About and contact
author:
  name:           'Richard Helper'
  url:            ' '

theme: hyde
# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
